name: HsRails
version: 1.4.0
description: High speed minecart rails
api-version: 1.20
main: xyz.misilelaboratory.hsrails.HsRails
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.0
commands:
  hsrails:
    description: Sets new minecart speed limit.
    usage: /hsrails <multiplier>
permissions:
  hsrails.cmd:
    description: Allows you to use speed cmd
    default: op